CoreDisc/CoreDisc-BE

- src/main/java/com/coredisc/CorediscApplication.java
- src/main/java/com/coredisc/domain/common/BaseEntity.java
BaseEntity 생성
Closes #2 
아래 두 속성만 만들었습니다.
- Created At
- updatedAt
> BaseEntity 생성

- src/main/java/com/coredisc/application/service/question/QuestionCommandService.java
- src/main/java/com/coredisc/application/service/question/QuestionCommandServiceImpl.java
- src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
- src/main/java/com/coredisc/common/converter/QuestionCategoryConverter.java
- src/main/java/com/coredisc/common/converter/QuestionConverter.java
- src/main/java/com/coredisc/common/exception/handler/QuestionHandler.java
- src/main/java/com/coredisc/domain/OfficialQuestion.java
- src/main/java/com/coredisc/domain/TodayQuestion.java
- src/main/java/com/coredisc/domain/category/Category.java
- src/main/java/com/coredisc/domain/category/CategoryRepository.java
- src/main/java/com/coredisc/domain/mapping/questionCategory/QuestionCategory.java
- src/main/java/com/coredisc/domain/mapping/questionCategory/QuestionCategoryRepository.java
- src/main/java/com/coredisc/domain/personalQuestion/PersonalQuestion.java
- src/main/java/com/coredisc/domain/personalQuestion/PersonalQuestionRepository.java
- src/main/java/com/coredisc/infrastructure/repository/category/CategoryRepositoryAdaptor.java
- src/main/java/com/coredisc/infrastructure/repository/category/JpaCategoryRepository.java
- src/main/java/com/coredisc/infrastructure/repository/question/JpaPersonalQuestionRepository.java
- src/main/java/com/coredisc/infrastructure/repository/question/PersonalQuestionRepositoryAdapter.java
- src/main/java/com/coredisc/infrastructure/repository/questionCategory/JpaQuestionCategoryRepository.java
- src/main/java/com/coredisc/infrastructure/repository/questionCategory/QuestionCategoryRepositoryAdapter.java
- src/main/java/com/coredisc/presentation/controller/QuestionController.java
- src/main/java/com/coredisc/presentation/controllerdocs/QuestionControllerDocs.java
- src/main/java/com/coredisc/presentation/dto/question/QuestionRequestDTO.java
- src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
내가 작성한 커스텀 질문 저장 API 구현
Closes #15
- 기본 repository는 이처럼 도메인명의 패키지를 하나 만들고 그 안에 넣는게 맞을까요? (먼저 커밋한 분의 코드를 참고하긴 했습니다.)
- 이런 구조는 처음이라 제대로 작성한건지 잘 모르겠습니다.. 적극적인 피드백 환영합니다.
> 커스텀 질문 저장(생성) API 구현

- src/main/java/com/coredisc/application/service/member/MemberQueryServiceImpl.java
불필요한 import문 삭제했습니다. 
Closes #45 
related to #31
이전 PR merge 중에 삭제가 누락된 부분이 있어서 해당 부분 수정했습니다.
> Fix: 불필요한 import문 삭제

- src/main/java/com/coredisc/application/service/question/QuestionQueryService.java
- src/main/java/com/coredisc/application/service/question/QuestionQueryServiceImpl.java
- src/main/java/com/coredisc/common/converter/QuestionConverter.java
- src/main/java/com/coredisc/domain/officialQuestion/OfficialQuestionRepository.java
- src/main/java/com/coredisc/domain/personalQuestion/PersonalQuestionRepository.java
- src/main/java/com/coredisc/infrastructure/repository/question/JpaOfficialQuestionRepository.java
- src/main/java/com/coredisc/infrastructure/repository/question/OfficialQuestionRepositoryAdapter.java
- src/main/java/com/coredisc/infrastructure/repository/question/PersonalQuestionRepositoryAdapter.java
- src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryOfficialQuestionRepository.java
- src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryOfficialQuestionRepositoryImpl.java
- src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryPersonalQuestionRepository.java
- src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryPersonalQuestionRepositoryImpl.java
- src/main/java/com/coredisc/presentation/controller/QuestionController.java
- src/main/java/com/coredisc/presentation/controllerdocs/QuestionControllerDocs.java
- src/main/java/com/coredisc/presentation/dto/category/CategoryResponseDTO.java
- src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
- 기본 질문 조회
- 기본 질문 검색
- 내가 발행한 공유 질문 조회
Closes #44
인기 질문, 내가 저장한 공유 질문은 로직 고민을 더 해야할 것 같아서 제외헀습니다.
> Feat: 질문 조회 관련 API 구현

- src/main/java/com/coredisc/application/service/question/QuestionQueryService.java
- src/main/java/com/coredisc/application/service/question/QuestionQueryServiceImpl.java
- src/main/java/com/coredisc/common/converter/QuestionConverter.java
- src/main/java/com/coredisc/domain/todayQuestion/TodayQuestion.java
- src/main/java/com/coredisc/presentation/controller/QuestionController.java
- src/main/java/com/coredisc/presentation/controllerdocs/QuestionControllerDocs.java
- src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
오늘 기준 선택한 고정&랜덤 질문 조회 API 구현
Closes #55
> feat: 선택한 고정&랜덤 질문 조회 API 구현

- .github/workflows/dev_deploy.yml
- Dockerfile
CI/CD 파이프라인을 구축했습니다.
Closes #67
제발 되길
> Ci: ci/cd 파이프라인 구축

- .github/workflows/dev_deploy.yml
> Ci: tag 이름에 latest 명시

- .github/workflows/dev_deploy.yml
> Feat: docker 워크플로우 수정

- .github/workflows/dev_deploy.yml
docker-compose.yml 경로 추가
Closes #67
> Ci: docker-compose.yml 경로 추가

- src/main/java/com/coredisc/presentation/controllerdocs/CategoryControllerDocs.java
- src/main/java/com/coredisc/presentation/controllerdocs/QuestionControllerDocs.java
프론트분들이 연동하지 않도록 수정중인 API 스웨거에 수정중 표시를 하였습니다. 
Closes #62
> Docs: 질문 조회 관련 API 수정중 표시 추가

- src/main/java/com/coredisc/application/service/member/MemberCommandService.java
- src/main/java/com/coredisc/application/service/member/MemberCommandServiceImpl.java
- src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
- src/main/java/com/coredisc/common/converter/ProfileImgConverter.java
- src/main/java/com/coredisc/domain/profileImg/ProfileImg.java
- src/main/java/com/coredisc/domain/profileImg/ProfileImgRepository.java
- src/main/java/com/coredisc/infrastructure/aws/s3/AmazonS3Manager.java
- src/main/java/com/coredisc/infrastructure/repository/profileImg/ProfileImgRepositoryAdaptor.java
- src/main/java/com/coredisc/presentation/controller/MemberController.java
- src/main/java/com/coredisc/presentation/controllerdocs/MemberControllerDocs.java
사용자 프로필 사진 변경 API를 구현했습니다.
Closes #58
> Feat: 사용자 프로필 사진 변경 API 구현

- src/main/java/com/coredisc/application/service/question/QuestionQueryService.java
- src/main/java/com/coredisc/application/service/question/QuestionQueryServiceImpl.java
- src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
- src/main/java/com/coredisc/common/converter/QuestionConverter.java
- src/main/java/com/coredisc/domain/mapping/memberOfficialQuestion/MemberOfficialQuestionRepository.java
- src/main/java/com/coredisc/domain/officialQuestion/OfficialQuestionRepository.java
- src/main/java/com/coredisc/infrastructure/repository/question/MemberOfficialQuestionRepositoryAdapter.java
- src/main/java/com/coredisc/infrastructure/repository/question/OfficialQuestionRepositoryAdapter.java
- src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryMemberOfficialQuestionRepository.java
- src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryMemberOfficialQuestionRepositoryImpl.java
- src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryOfficialQuestionRepository.java
- src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryOfficialQuestionRepositoryImpl.java
- src/main/java/com/coredisc/presentation/controller/QuestionController.java
- src/main/java/com/coredisc/presentation/controllerdocs/QuestionControllerDocs.java
- src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
- 내가 저장한 타사용자의 공유 질문 목록 조회
- 인기 질문 목록 조회
Closes #86 
> Feat: 저장한 공유 질문, 인기 질문 조회 API 구현

- src/main/java/com/coredisc/application/service/auth/SocialAuthServiceImpl.java
- src/main/java/com/coredisc/common/converter/MemberConverter.java
- src/main/java/com/coredisc/common/properties/SocialProperties.java
- src/main/java/com/coredisc/presentation/controller/AuthController.java
- src/main/java/com/coredisc/presentation/controllerdocs/AuthControllerDocs.java
- src/main/java/com/coredisc/presentation/dto/auth/NaverUserInfo.java
- 기존에 개발해놓은 소셜 로그인 로직에 Naver 소셜 로그인 로직을 추가 작성했습니다.
Closes #104
> Feat: Naver 소셜 로그인 API 구현

- src/main/java/com/coredisc/application/service/question/QuestionCommandService.java
- src/main/java/com/coredisc/application/service/question/QuestionCommandServiceImpl.java
- src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
- src/main/java/com/coredisc/common/converter/QuestionConverter.java
- src/main/java/com/coredisc/domain/mapping/memberOfficialQuestion/MemberOfficialQuestion.java
- src/main/java/com/coredisc/presentation/controller/QuestionController.java
- src/main/java/com/coredisc/presentation/controllerdocs/QuestionControllerDocs.java
- src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
공유질문 즐겨찾기 추가하기 
공유질문 즐겨찾기 삭제하기
Closes #65 
> Feat: 저장한 공유질문 즐겨찾기 추가/삭제 API 구현

- src/main/java/com/coredisc/common/converter/QuestionConverter.java
- src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryMemberOfficialQuestionRepositoryImpl.java
- src/main/java/com/coredisc/presentation/dto/question/QuestionResponseDTO.java
- 커서 페이징 시 cursorId 기준을 바꿨습니다.
- 프론트분들이 이해하기 쉽게 반환 DTO를 수정했습니다. 
Closes #109 
> Refactor: 공유 질문 API 로직 수정

- src/main/java/com/coredisc/application/service/comment/CommentCommandService.java
- src/main/java/com/coredisc/application/service/comment/CommentCommandServiceImpl.java
- src/main/java/com/coredisc/application/service/comment/CommentQueryService.java
- src/main/java/com/coredisc/application/service/comment/CommentQueryServiceImpl.java
- src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
- src/main/java/com/coredisc/common/converter/CommentConverter.java
- src/main/java/com/coredisc/common/exception/handler/CommentHandler.java
- src/main/java/com/coredisc/domain/Comment.java
- src/main/java/com/coredisc/domain/comment/CommentRepository.java
- src/main/java/com/coredisc/infrastructure/repository/comment/CommentRepositoryAdaptor.java
- src/main/java/com/coredisc/infrastructure/repository/comment/JpaCommentRepository.java
- src/main/java/com/coredisc/infrastructure/repository/comment/queryDsl/CommentQueryRepository.java
- src/main/java/com/coredisc/infrastructure/repository/comment/queryDsl/commentQueryRepositoryImpl.java
- src/main/java/com/coredisc/presentation/controller/CommentController.java
- src/main/java/com/coredisc/presentation/controllerdocs/CommentControllerDocs.java
- src/main/java/com/coredisc/presentation/dto/comment/CommentRequestDTO.java
- src/main/java/com/coredisc/presentation/dto/comment/CommentResponseDTO.java
- 댓글 기능 구현
- 대댓글 기능 구현
ex) 로그인 API 구현, validation 추가 등
Closes #80 
댓글과 대댓글은 api를 분리하여 조회하도록 변경했습니다.
> Feat: 댓글 api 구현

- src/main/java/com/coredisc/application/service/follow/FollowQueryService.java
- src/main/java/com/coredisc/application/service/follow/FollowQueryServiceImpl.java
- src/main/java/com/coredisc/common/converter/FollowConverter.java
- src/main/java/com/coredisc/presentation/controller/FollowController.java
- src/main/java/com/coredisc/presentation/controllerdocs/FollowControllerDocs.java
- src/main/java/com/coredisc/presentation/dto/follow/FollowResponseDTO.java
타사용자의 팔로워,팔로잉 목록 조회 API 구현
Closes #127
> Feat: 타사용자의 팔로워,팔로잉 목록 조회 API 구현

- src/main/java/com/coredisc/application/service/auth/AuthQueryServiceImpl.java
- src/main/java/com/coredisc/domain/member/MemberRepository.java
- src/main/java/com/coredisc/infrastructure/repository/member/JpaMemberRepository.java
- src/main/java/com/coredisc/infrastructure/repository/member/MemberRepositoryAdaptor.java
- src/main/java/com/coredisc/presentation/dto/auth/AuthRequestDTO.java
요청 dto가 수정됨에 따라 리팩토링을 진행했습니다.
Closes #134 
> Refactor: 비밀번호 변경을 위한 사용자 검증 요청 dto 및 로직 수정

- src/main/java/com/coredisc/presentation/dto/auth/AuthRequestDTO.java
회원가입 요청 dto에 필드 검증 어노테이션을 추가했습니다.
Closes #136
> Refactor: 회원가입 요청 dto 검증 어노테이션 추가

- src/main/java/com/coredisc/application/service/like/PostLikeCommandService.java
- src/main/java/com/coredisc/application/service/like/PostLikeCommandServiceImpl.java
- src/main/java/com/coredisc/application/service/post/PostQueryServiceImpl.java
- src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
- src/main/java/com/coredisc/common/converter/PostConverter.java
- src/main/java/com/coredisc/common/exception/handler/LikeHandler.java
- src/main/java/com/coredisc/domain/post/Post.java
- src/main/java/com/coredisc/domain/post/PostLike.java
- src/main/java/com/coredisc/domain/post/PostLikeRepository.java
- src/main/java/com/coredisc/infrastructure/repository/post/queryDsl/QueryPostRepositoryImpl.java
- src/main/java/com/coredisc/infrastructure/repository/postLike/JpaPostLikeRepository.java
- src/main/java/com/coredisc/infrastructure/repository/postLike/PostLikeRepositoryAdaptor.java
- src/main/java/com/coredisc/presentation/controller/PostController.java
- src/main/java/com/coredisc/presentation/controllerdocs/PostControllerDocs.java
- src/main/java/com/coredisc/presentation/dto/post/PostResponseDTO.java
좋아요 추가, 삭제 기능 구현
중간에 테스트 도중 문제가 발생해서 게시글 상세 조회 관련 코드 일부 수정했습니다.
Closes #130 
토글 -> 좋아요 테이블 추가, 삭제 api 2개로 분리
토글 방식은 - 프론트측 코드가 편해지지만 restful 한 방식이 아니라고 생각이 들어 변경했습니다.
> Feat : 좋아요 기능 구현

- src/main/java/com/coredisc/application/service/member/MemberQueryService.java
- src/main/java/com/coredisc/application/service/member/MemberQueryServiceImpl.java
- src/main/java/com/coredisc/infrastructure/repository/question/CustomQuestionRepository.java
- src/main/java/com/coredisc/infrastructure/repository/question/CustomQuestionRepositoryAdapter.java
- src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryCustomQuestionRepository.java
- src/main/java/com/coredisc/infrastructure/repository/question/querydsl/QueryCustomQuestionRepositoryImpl.java
- src/main/java/com/coredisc/presentation/controller/MemberController.java
- src/main/java/com/coredisc/presentation/controllerdocs/MemberControllerDocs.java
- src/main/java/com/coredisc/presentation/dto/member/MemberResponseDTO.java
- 마이홈 - 내가 작성한 질문들 API 구현했습니다. 
Closes #119 
> Feat: 마이홈 - 내가 작성한 질문들 조회 API 구현

- build.gradle
- docker-compose.yml
- monitoring/prometheus/prometheus.yml
- prometheus.yml
- src/main/java/com/coredisc/config/SecurityConfig.java
ex) 로그인 API 구현, validation 추가 등
Closes #
> Feat: 모니터링 시스템 구축

- src/main/java/com/coredisc/application/service/question/QuestionCommandServiceImpl.java
- src/main/java/com/coredisc/application/service/question/QuestionQueryServiceImpl.java
- src/main/java/com/coredisc/common/apiPayload/status/ErrorStatus.java
기본 제공 질문은 공유 질문으로 저장 못하게 막았습니다.
질문 목록 조회 시 기본 질문은 "CANNOT_SAVE"로 반환하게 했습니다.
추후 ENUM으로 리팩토링 고민중입니다. 
Closes #173 
> Refactor: 기본 제공 질문 관련 수정

- src/main/java/com/coredisc/common/converter/TermsConverter.java
- src/main/java/com/coredisc/domain/common/enums/TermsType.java
- src/main/java/com/coredisc/presentation/dto/terms/TermsResponseDTO.java
- 약관 데이터 DB 삽입
- TermsType title 수정
- 응답 dto, converter 수정
Closes #176 
> Refactor: TermsType title 수정 및 응답 수정

- src/main/java/com/coredisc/common/converter/PostConverter.java
- src/main/java/com/coredisc/presentation/dto/post/PostResponseDTO.java
조회 응답 데이터 수정 및 삭제 - username , publicity ,statics
Closes #
> Refactor: 게시글 조회 응답 관련 api 수정
